### ISSUE TITLE
New formbuilder

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/edd-checkout-fields#146]
By the title of this issue, this is going to be a big one.

The current formbuilder that's bundled both in CFM and FES is written in a way that makes issues such as #127, #128 and #144 nearly _impossible_ because of the markup that it generates.

An example being,
```php
<div class="cfm-form-rows">
	<label><?php _e( 'Rows', 'edd_cfm' ); ?></label>
	<input type="text" class="smallipopInput" name="<?php echo $rows_name; ?>" title="Number of rows in textarea" value="<?php echo $rows_value; ?>" />
</div>

<div class="cfm-form-rows">
	<label><?php _e( 'Columns', 'edd_cfm' ); ?></label>
	<input type="text" class="smallipopInput" name="<?php echo $cols_name; ?>" title="Number of columns in textarea" value="<?php echo $cols_value; ?>" />
</div>

<div class="cfm-form-rows">
	<label><?php _e( 'Placeholder text', 'edd_cfm' ); ?></label>
	<input type="text" class="smallipopInput" name="<?php echo $placeholder_name; ?>" title="text for HTML5 placeholder attribute" value="<?php echo $placeholder_value; ?>" />
</div>

<div class="cfm-form-rows">
	<label><?php _e( 'Default value', 'edd_cfm' ); ?></label>
	<input type="text" class="smallipopInput" name="<?php echo $default_name; ?>" title="the default value this field will have" value="<?php echo $default_value; ?>" />
</div>
```

There isn't a nice, clean way to target any of these elements specifically, we don't have any class names of IDs attached to these fields.  Granted a `neme` attribute is present on these fields, but that still gives us very little to work with.

Also, all the methods in `CFM_Formbuilder_Templates` do not have filters which means there can be no change to the markup.

As part of #144, the goal is to clean up the formbuilder and provider and more intuitive UI to the user when interacting with the formbuilder.  Currently, the user sees a ton of options upon adding a field, i.e. `CSS Class Name` or `Size`.  With #144, the aim is to separate out the settings into three tabs: `General`, `Styling` and `Advanced`.  This is not possible with the current way the formbuilder has been written.

After speaking with @cklosowski on this topic, it was agreed that the best way to tackle a task like this would be to rewrite the formbuilder.  As aforementioned, this is a big task and there's no doubt users would have written custom fields for CFM; with that, we _need_ to ensure full backwards compatibility.

After an initial discussion with @cklosowski, I proposed that make use of the versioning of each field and when loading in the fields for the formbuilder, we check if the version of the field is `< 2.0`.  If this is case, then we'd load `CFM_Formbuilder_v1` and render out the template using the old templates.  `CFM_Formbuilder_v1` would just be a clone of the existing formbuilder along with `CFM_Formbuilder_Templates_v1`.

In terms of the data structure, the meta is fine and we don't need any sort of upgrade routine to change the data in the database.

## To-Do List

- [ ] Introduce new `CFM_Formbuilder` and `CFM_Field` class, this will rewrite the method that renders the `Checkout Form` page and use the new structure of the `CFM_Field` class.
- [ ] Introduce new `CFM_Formbuilder_Templates` class which restructures the output of all the markup to be more semantic and also allow better targeting via CSS and JavaScript.
- [ ] The formbuilder templates should not be strongly coupled to the `render_formbuilder_field` function, instead all of the template fields that need to be loaded should be stored in an array of the class inside a subarray of `general`, `styling`, and `advanced`.  This would have filters so going forward, would allow easy customisation of the layout of the input fields as well as easily add input fields to existing form fields, e.g. add a `CSS Class Name` input to the `First Name` field would as easy as this:
```php
function add_class_input_to_field( $settings ) {
	$settings[] = 'css_class_setting';
	return $settings;
}
add_filter( 'edd_cfm_field_first_name_settings', 'add_class_input_to_field' );
```
- [ ] Add logic for backwards compatibility to ensure older custom fields continue to work the same way as before
- [ ] Update all fields (including custom fields of EDD extensions) to ensure they adhere to the new structure of the formbuilder.
- [ ] All new fields shouldn't use jQuery Smallipop but instead use the tooltips that are already part of EDD core for consistency between extensions.

**Comment by sunnyratilal** [comment]
After discussing this with @cklosowski, we've decided that will first be implemented in CFM and then ported across to FES.
